name: 'Image Optimizer'
description: 'Compress and optimize images in your repository'
runs:
  using: 'node16'
  main: 'index.js'
inputs:
  repo-token:
    description: 'Repository token'
    required: true

branding:
  icon: "image"
  color: "gray-dark"
